import Head from "next/head";
import Header from "../components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Image from "next/image";
import ImageCarousel from "../components/Carousel/ImageCarousel";
import Link from "next/link";

export default function Home() {
	const images = [
		"/slider2.jpeg",
		"/slider3.jpeg",
		"/fundraising.jpg",
		"/charity-better.jpg",
		"/community-fair.jpg",
	];

	return (
		<>
			<Head>
				<title>Fountain of Love</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<>
				<main>
					<div className="relative overflow-hidden bg-white">
						<div className="pb-80 pt-16 sm:pb-40 sm:pt-24 lg:pb-48 lg:pt-40">
							<div className="relative mx-auto max-w-7xl px-4 sm:static sm:px-6 lg:px-8">
								<div className="mx-auto max-w-2xl lg:mx-0 lg:max-w-xl">
									<h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
										Making a Difference, One Heart at a Time
									</h1>
									<p className="mt-6 text-lg leading-8 text-gray-600">
										Welcome to Fountain of Love: Where Compassion Flows
									</p>
									<div className="mt-10 flex items-center gap-x-6">
										<Link
											href="/about"
											className="rounded-md bg-indigo-600 px-3.5 py-1.5 text-base font-semibold leading-7 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
											Discover more
										</Link>
										<Link
											href="/donate"
											className="text-base font-semibold leading-7 text-gray-900">
											Donate <span aria-hidden="true">→</span>
										</Link>
									</div>
								</div>
							</div>
							<div className="pr-8 lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
								<ImageCarousel images={images} interval={3000} />
							</div>
						</div>
					</div>

					{/* Testimonial/stats section */}
					<div className="relative mt-20">
						<div className="lg:mx-auto lg:grid lg:max-w-7xl lg:grid-cols-2 lg:items-start lg:gap-24 lg:px-8">
							<div className="relative sm:py-16 lg:py-0">
								<div
									aria-hidden="true"
									className="hidden sm:block lg:absolute lg:inset-y-0 lg:right-0 lg:w-screen">
									<div className="absolute inset-y-0 right-1/2 w-full rounded-r-3xl bg-gray-50 lg:right-72" />
									<svg
										className="absolute top-8 left-1/2 -ml-3 lg:-right-8 lg:left-auto lg:top-12"
										width={404}
										height={392}
										fill="none"
										viewBox="0 0 404 392">
										<defs>
											<pattern
												id="02f20b47-fd69-4224-a62a-4c9de5c763f7"
												x={0}
												y={0}
												width={20}
												height={20}
												patternUnits="userSpaceOnUse">
												<rect
													x={0}
													y={0}
													width={4}
													height={4}
													className="text-gray-200"
													fill="currentColor"
												/>
											</pattern>
										</defs>
										<rect
											width={404}
											height={392}
											fill="url(#02f20b47-fd69-4224-a62a-4c9de5c763f7)"
										/>
									</svg>
								</div>
								<div className="relative mx-auto max-w-md px-6 sm:max-w-3xl lg:max-w-none lg:px-0 lg:py-20">
									{/* Testimonial card*/}
									<div className="relative overflow-hidden rounded-2xl pt-64 pb-10 shadow-xl">
										<Image
											className="absolute inset-0 h-full w-full object-cover"
											src="/volunteer.jpg"
											width={500}
											height={500}
											alt=""
										/>
									</div>
								</div>
							</div>

							<div className="relative mx-auto max-w-md px-6 sm:max-w-3xl lg:px-0">
								{/* Content area */}
								<div className="pt-12 sm:pt-16 lg:pt-20">
									<h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
										Transforming Lives and Nurturing Dreams
									</h2>
									<div className="mt-6 space-y-6 text-gray-500">
										<p className="text-lg">
											Sagittis scelerisque nulla cursus in enim consectetur quam. Dictum urna sed
											consectetur neque tristique pellentesque. Blandit amet, sed aenean erat arcu
											morbi. Cursus faucibus nunc nisl netus morbi vel porttitor vitae ut. Amet
											vitae fames senectus vitae.
										</p>
										<p className="text-base leading-7">
											Rhoncus nisl, libero egestas diam fermentum dui. At quis tincidunt vel
											ultricies. Vulputate aliquet velit faucibus semper. Pellentesque in venenatis
											vestibulum consectetur nibh id. In id ut tempus egestas. Enim sit aliquam nec,
											a. Morbi enim fermentum lacus in. Viverra.
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>

					{/* CTA section */}
					<div className="relative mt-24 sm:mt-32 sm:py-16">
						<div aria-hidden="true" className="hidden sm:block">
							<div className="absolute inset-y-0 left-0 w-1/2 rounded-r-3xl bg-gray-50" />
							<svg
								className="absolute top-8 left-1/2 -ml-3"
								width={404}
								height={392}
								fill="none"
								viewBox="0 0 404 392">
								<defs>
									<pattern
										id="8228f071-bcee-4ec8-905a-2a059a2cc4fb"
										x={0}
										y={0}
										width={20}
										height={20}
										patternUnits="userSpaceOnUse">
										<rect
											x={0}
											y={0}
											width={4}
											height={4}
											className="text-gray-200"
											fill="currentColor"
										/>
									</pattern>
								</defs>
								<rect width={404} height={392} fill="url(#8228f071-bcee-4ec8-905a-2a059a2cc4fb)" />
							</svg>
						</div>
						<div className="mx-auto max-w-md px-6 sm:max-w-3xl lg:max-w-7xl lg:px-8">
							<div className="relative overflow-hidden rounded-2xl bg-blue-500 px-6 py-10 shadow-xl sm:px-12 sm:py-20">
								<div aria-hidden="true" className="absolute inset-0 -mt-72 sm:-mt-32 md:mt-0">
									<svg
										className="absolute inset-0 h-full w-full"
										preserveAspectRatio="xMidYMid slice"
										xmlns="http://www.w3.org/2000/svg"
										fill="none"
										viewBox="0 0 1463 360">
										<path
											className="text-blue-400 text-opacity-40"
											fill="currentColor"
											d="M-82.673 72l1761.849 472.086-134.327 501.315-1761.85-472.086z"
										/>
										<path
											className="text-blue-600 text-opacity-40"
											fill="currentColor"
											d="M-217.088 544.086L1544.761 72l134.327 501.316-1761.849 472.086z"
										/>
									</svg>
								</div>
								<div className="relative">
									<div className="sm:text-center">
										<h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
											Get notified when we&rsquo;re launching.
										</h2>
										<p className="mx-auto mt-6 max-w-2xl text-lg text-rose-100">
											Sagittis scelerisque nulla cursus in enim consectetur quam. Dictum urna sed
											consectetur neque tristique pellentesque.
										</p>
									</div>
									<form action="#" className="mt-12 sm:mx-auto sm:flex sm:max-w-lg">
										<div className="min-w-0 flex-1">
											<label htmlFor="cta-email" className="sr-only">
												Email address
											</label>
											<input
												id="cta-email"
												type="email"
												className="block w-full rounded-md border border-transparent px-5 py-3 text-base text-gray-900 placeholder-gray-500 shadow-sm focus:border-transparent focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-rose-500"
												placeholder="Enter your email"
											/>
										</div>
										<div className="mt-4 sm:mt-0 sm:ml-3">
											<button
												type="submit"
												className="block w-full rounded-md border border-transparent bg-gray-900 px-5 py-3 text-base font-medium text-white shadow hover:bg-black focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-rose-500 sm:px-10">
												Notify me
											</button>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</main>
			</>
			<Footer />
		</>
	);
}
