import Head from "next/head";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Image from "next/image";
import ImageCarousel from "@/components/Carousel/ImageCarousel";
import Link from "next/link";

const projects = [
	{
		id: 1,
		title: "Community Event in Lagos, Nigeria",
		href: "#",
		date: "Mar 16, 2020",
		datetime: "2020-03-16",
		category: { name: "Article", href: "/events" },
		imageUrl: "/slider2.jpeg",
		preview:
			"In Lagos, the Fountain of Love's event radiated unity and giving, drawing over 300 locals for a community day filled with shared necessities and strengthened bonds.",
	},
	{
		id: 2,
		title: "Community Event in Omaha, Nebraska",
		href: "#",
		date: "Mar 10, 2020",
		datetime: "2020-03-10",
		category: { name: "Video", href: "/events" },
		imageUrl: "/event9.jpeg",
		preview:
			"In Omaha, Fountain of Love celebrated unity and generosity at Benson Park, with a hundred locals gathering for a day of sharing essential goods and fostering community spirit.",
	},
];

const photos = [
	{
		title: "Providing for the elderly",
		size: "3.9 MB",
		source: "/event5.jpeg",
	},
	{
		title: "Donations",
		size: "3.9 MB",
		source: "/donations2.jpg",
	},
	{
		title: "Fountain of Love Crew in Lagos",
		size: "3.9 MB",
		source: "/fol-crew.jpg",
	},
	{
		title: "Providing for the elderly",
		size: "3.9 MB",
		source: "/event2.jpeg",
	},
	{
		title: "Providing for the elderly",
		size: "3.9 MB",
		source: "/event4.jpeg",
	},
	{
		title: "Providing for the elderly",
		size: "3.9 MB",
		source: "/event7.jpeg",
	},
	{
		title: "Providing for the elderly",
		size: "3.9 MB",
		source: "/event9.jpeg",
	},
	{
		title: "Providing for the elderly",
		size: "3.9 MB",
		source: "/event10.jpeg",
	},
	// More photos...
];

const images = [
	"/event1.jpeg",
	"/event2.jpeg",
	"/fundraising.jpg",
	"/charity-better.jpg",
	"/community-fair.jpg",
];

export default function Home() {
	return (
		<>
			<Head>
				<title>Fountain of Love</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<>
				<main>
					<section>
						<div className="relative overflow-hidden bg-white">
							<div className="pb-80 pt-16 sm:pb-40 sm:pt-24 lg:pb-48 lg:pt-40">
								<div className="relative mx-auto max-w-7xl px-4 sm:static sm:px-6 lg:px-8">
									<div className="mx-auto max-w-2xl lg:mx-0 lg:max-w-xl">
										<h1 className="text-4xl font-sans font-bold tracking-tight text-gray-900 sm:text-6xl">
											Making a Difference, One Heart at a Time
										</h1>
										<p className="mt-6 text-lg font-sans leading-8 text-gray-600">
											Welcome to Fountain of Love: Where Compassion Flows
										</p>
										<div className="mt-10 flex items-center gap-x-6">
											<Link
												href="/about"
												className="rounded-md font-sans bg-cyan-600 px-3.5 py-1.5 text-base font-semibold leading-7 text-white shadow-sm hover:bg-cyan-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
												Discover more
											</Link>
											<Link
												href="/donate"
												className="text-base font-sans font-semibold leading-7 text-gray-900">
												Donate <span aria-hidden="true">→</span>
											</Link>
										</div>
									</div>
								</div>
								<div className="hidden mt-12 ml-32 sm:block lg:hidden pr-8">
									{/* iPad View */}
									<ImageCarousel images={images} interval={3000} />
								</div>

								<div className="hidden lg:block pr-8 lg:absolute lg:inset-y-0 lg:right-0 lg:w-[43%] 2xl:w-[65%]">
									{/* Desktop View */}
									<ImageCarousel images={images} interval={3000} />
								</div>

								<div className="block mt-12 ml-8 px-4 w-[80%] sm:hidden">
									{/* Mobile View */}
									<ImageCarousel images={images} interval={3000} />
								</div>
							</div>
						</div>
					</section>

					<section>
						{/* Blog section */}
						<div className="relative py-8 sm:py-24 lg:py-32">
							<div className="relative">
								<div className="mx-auto max-w-md text-center sm:max-w-3xl lg:max-w-[90rem]">
									<h2 className="text-lg font-sans font-semibold text-cyan-600">Volunteer</h2>
									<p className="mt-2 text-3xl font-sans font-bold tracking-tight text-gray-900 sm:text-4xl">
										Our recent projects
									</p>
								</div>
								<div className="mx-auto mt-12 grid max-w-md gap-16 px-6 sm:max-w-lg lg:max-w-7xl lg:grid-cols-2">
									{projects.map((project) => (
										<div
											key={project.id}
											className="flex flex-col overflow-hidden rounded-lg shadow-lg">
											<div className="flex-shrink-0">
												<Image
													className="h-96 w-full block object-cover"
													src={project.imageUrl}
													alt=""
													width={500}
													height={500}
												/>
											</div>
											<div className="flex flex-1 flex-col justify-between bg-white p-6">
												<div className="flex-1">
													<a href={project.href} className="mt-2 block">
														<p className="text-xl font-sans font-semibold text-gray-900">
															{project.title}
														</p>
														<p className="mt-3 text-base font-sans text-gray-500">
															{project.preview}
														</p>
													</a>
												</div>
												<div className="mt-6 flex items-center">
													<div>
														<div className="flex font-sans space-x-1 text-sm text-gray-500">
															<time dateTime={project.datetime}>{project.date}</time>
														</div>
													</div>
												</div>
											</div>
										</div>
									))}
								</div>
							</div>
						</div>
					</section>

					<section>
						<div className="relative">
							<div className="mx-auto max-w-md text-center sm:max-w-3xl lg:max-w-6xl">
								<h2 className="text-5xl mt-8 font-bold text-black mb-16 font-sans">Our Impact</h2>
								<ul
									role="list"
									className="px-4 grid grid-cols-2 gap-x-2 gap-y-8 sm:grid-cols-3 sm:gap-x-6 lg:grid-cols-4 xl:gap-x-8">
									{photos.map((photo) => (
										<li key={photo.source} className="relative">
											<div className="group aspect-w-10 h-64 block w-full overflow-hidden rounded-lg">
												<Image
													src={photo.source}
													alt=""
													width={500}
													height={500}
													className="pointer-events-none object-cover"
												/>
												<button type="button" className="absolute inset-0 focus:outline-none">
													<span className="sr-only">View details for {photo.title}</span>
												</button>
											</div>
										</li>
									))}
								</ul>
							</div>
						</div>
					</section>

					<section>
						{/* Testimonial/stats section */}
						<div className="relative pb-48 pt-16 sm:pb-40 sm:pt-24 -mt-12">
							<div className="lg:mx-auto lg:grid lg:max-w-7xl lg:grid-cols-2 lg:items-start lg:gap-24 lg:px-8">
								<div className="relative sm:py-16 lg:py-0">
									<div className="relative mt-20 mx-auto max-w-md px-6 sm:max-w-3xl lg:max-w-none lg:px-0 lg:py-20">
										{/* Testimonial card*/}
										<div className="overflow-hidden rounded-2xl pt-72 pb-10 shadow-xl">
											<Image
												className="absolute inset-0 h-full w-full object-cover sm:"
												src="/event3.jpeg"
												width={500}
												height={500}
												alt=""
											/>
										</div>
									</div>
								</div>

								<div className="relative mx-auto max-w-md px-6 sm:max-w-3xl lg:px-0">
									{/* Content area */}
									<div className="pt-12 sm:pt-16 lg:pt-20">
										<h2 className="text-2xl font-sans font-bold tracking-tight text-black sm:text-5xl">
											Get Involved With Us
										</h2>
										<div className="mt-6 space-y-6 text-gray-500">
											<p className="text-lg font-sans">
												Join hands with Fountain of Love and be a part of this profound journey.
											</p>
											<p className="text-lg font-sans">
												There are multiple ways to contribute. Whether through donations,
												volunteering, or corporate partnerships, your support becomes the lifeblood
												of our endeavors. By collaborating with us, you have the opportunity to
												change lives and build bridges of hope that will endure for generations to
												come. You can donate your time, resources, or skills.
											</p>
											<p className="text-lg font-sans">
												Join us as a volunteer, as a corporate partner, or as a benefactor. Each
												role is crucial in our mission to bring love and hope to those who need it
												the most.
											</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</section>

					{/* CTA section */}
					<div className="relative -mt-12 sm:py-16">
						<div className="mx-auto max-w-md px-6 sm:max-w-3xl lg:max-w-7xl lg:px-8">
							<div className="relative overflow-hidden rounded-2xl bg-cyan-600 px-6 py-10 shadow-xl sm:px-12 sm:py-20">
								<div className="relative">
									<div className="sm:text-center">
										<h2 className="text-3xl font-sans font-bold tracking-tight text-white sm:text-4xl">
											Get notified when we&rsquo;re launching near you.
										</h2>
										<p className="mx-auto font-sans mt-6 max-w-2xl text-lg text-rose-100">
											Stay connected with our mission and be the first to know about our upcoming
											events and initiatives.
										</p>
									</div>
									<form action="#" className="mt-12 sm:mx-auto sm:flex sm:max-w-lg">
										<div className="min-w-0 flex-1">
											<label htmlFor="cta-email" className="sr-only">
												Email address
											</label>
											<input
												id="cta-email"
												type="email"
												className="block font-sans w-full rounded-md border border-transparent px-5 py-3 text-base text-gray-900 placeholder-gray-500 shadow-sm focus:border-transparent focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-rose-500"
												placeholder="Enter your email"
											/>
										</div>
										<div className="mt-4 sm:mt-0 sm:ml-3">
											<button
												type="submit"
												className="block w-full font-sans rounded-md border border-transparent bg-gray-900 px-5 py-3 text-base font-medium text-white shadow hover:bg-black focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-rose-500 sm:px-10">
												Notify me
											</button>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</main>
			</>
			<Footer />
		</>
	);
}
